import React from 'react';
import { FaGuitar, FaDrum, FaMusic, FaSaxophone, FaPiano, FaBanjo, FaViolin } from 'react-icons/fa'; // Para algunos instrumentos
import { mdiViolin, mdiTrumpet, mdiTrombone, mdiClarinet, mdiFlute, mdiAccordion, mdiGuitarAcoustic, mdiSaxophone, mdiHarmonica, mdiPiano, mdiDrum, mdiTriangle } from '@mdi/js'; // Material Design Icons
import Icon from '@mdi/react'; // Para Material Design Icons

const instrumentIcons = {
  "Violín": <Icon path={mdiViolin} size={1} />,
  "Viola": <FaMusic />, 
  "Violonchelo": <FaMusic />,
  "Contrabajo": <FaMusic />,
  "Guitarra acústica": <Icon path={mdiGuitarAcoustic} size={1} />,
  "Guitarra eléctrica": <FaGuitar />,
  "Bajo eléctrico": <FaMusic />,
  "Arpa": <FaMusic />,
  "Banjo": <FaMusic />,
  "Mandolina": <FaMusic />,
  "Ukulele": <FaMusic />,
  "Cítara": <FaMusic />,
  "Laúd": <FaMusic />,
  "Sitar": <FaMusic />,
  "Koto": <FaMusic />,
  "Guzheng": <FaMusic />,
  "Flauta transversal": <Icon path={FaMusic} size={1} />,
  "Flauta dulce": <FaMusic />,
  "Clarinete": <Icon path={FaMusic} size={1} />,
  "Oboe": <FaMusic />,
  "Fagot": <FaMusic />,
  "Saxofón": <FaMusic />,
  "Piccolo": <FaMusic />,
  "Contrafagot": <FaMusic />,
  "Trompeta": <Icon path={mdiTrumpet} size={1} />,
  "Trombón": <Icon path={FaMusic} size={1} />,
  "Trompa": <FaMusic />,
  "Tuba": <FaMusic />,
  "Corneta": <FaMusic />,
  "Trompa francesa": <FaMusic />,
  "Batería": <Icon path={FaMusic} size={1} />,
  "Tambores": <Icon path={FaMusic} size={1} />,
  "Platillos": <FaMusic />,
  "Congas": <FaMusic />,
  "Bongos": <FaMusic />,
  "Djembé": <FaMusic />,
  "Cajón": <FaMusic />,
  "Xilófono": <FaMusic />,
  "Marimba": <FaMusic />,
  "Vibrafón": <FaMusic />,
  "Glockenspiel": <FaMusic />,
  "Timpani": <FaMusic />,
  "Campanas tubulares": <FaMusic />,
  "Piano acústico": <Icon path={mdiPiano} size={1} />,
  "Piano eléctrico": <Icon path={mdiPiano} size={1} />,
  "Teclado electrónico": <FaMusic />,
  "Órgano": <FaMusic />,
  "Sintetizador": <FaMusic />,
  "Clavicordio": <FaMusic />,
  "Acordeón": <Icon path={FaMusic} size={1} />,
  "Melódica": <FaMusic />,
  "Secuenciador": <FaMusic />,
  "Sampler": <FaMusic />,
  "Drum machine": <Icon path={FaMusic} size={1} />,
  "Theremin": <FaMusic />,
  "Controlador MIDI": <FaMusic />,
  "Didgeridoo": <FaMusic />,
  "Shamisen": <FaMusic />,
  "Balalaika": <FaMusic />,
  "Kora": <FaMusic />,
  "Erhu": <FaMusic />,
  "Bagpipes": <FaMusic />,
  "Tabla": <FaMusic />,
  "Oud": <FaMusic />,
  "Maracas": <FaMusic />,
  "Guiro": <FaMusic />,
  "Charango": <FaMusic />,
  "Panflute": <FaMusic />,
  "Harmónica": <Icon path={FaMusic} size={1} />,
  "Kalimba": <FaMusic />,
  "Steel drums": <FaMusic />,
  "Electro-acústicos": <FaMusic />
};

export default instrumentIcons;
